comet:
  _target_: lightning.pytorch.loggers.comet.CometLogger
  api_key: ${oc.env:COMET_API_TOKEN} # api key is loaded from environment variable
  project_name: ${project_name}
  save_dir: ${hydra:runtime.output_dir}/.comet_logs
  experiment_key: null # set to resume experiment
  offline: True